import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Classes extends StatelessWidget {
  const Classes({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1271,
          height: 874,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1272,
                  height: 874,
                  decoration: BoxDecoration(color: const Color(0xFFF8FAFC)),
                ),
              ),
              Positioned(
                left: 16,
                top: 107,
                child: Text(
                  'Mis Asignaturas',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 36,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.11,
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 160,
                child: Text(
                  'Selecciona una materia para ver tus evaluaciones y calificaciones',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 18,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.56,
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 220,
                child: Container(
                  width: 608,
                  height: 217,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 4),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 244,
                child: Text(
                  'Cálculo III',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 276,
                child: Text(
                  'Prof. Martinez - Aula 302',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 300,
                child: Text(
                  '10:00 AM',
                  style: TextStyle(
                    color: const Color(0xFFFD8305),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 551,
                top: 243,
                child: Text(
                  '85%',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFFFD8305),
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 542,
                top: 280,
                child: Text(
                  'Promedio',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 338,
                child: Text(
                  'Evaluaciones:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 155,
                top: 336,
                child: Text(
                  '4',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 500,
                top: 338,
                child: Text(
                  'Calificadas:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 590,
                top: 336,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 376,
                child: Container(
                  width: 556,
                  height: 37,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFF1F5F9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 393,
                child: Text(
                  'Ver detalles',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 580,
                top: 393,
                child: Container(
                  width: 20,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 648,
                top: 220,
                child: Container(
                  width: 608,
                  height: 217,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 4),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 244,
                child: Text(
                  'Física II',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 276,
                child: Text(
                  'Prof. Garcia - Aula 205',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 300,
                child: Text(
                  '2:00 PM',
                  style: TextStyle(
                    color: const Color(0xFF10B981),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1190,
                top: 243,
                child: Text(
                  '91%',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF10B981),
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 1174,
                top: 280,
                child: Text(
                  'Promedio',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 338,
                child: Text(
                  'Evaluaciones:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 787,
                top: 336,
                child: Text(
                  '4',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 1132,
                top: 338,
                child: Text(
                  'Calificadas:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1222,
                top: 336,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 376,
                child: Container(
                  width: 556,
                  height: 37,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFF1F5F9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 393,
                child: Text(
                  'Ver detalles',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1212,
                top: 393,
                child: Container(
                  width: 20,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 16,
                top: 461,
                child: Container(
                  width: 608,
                  height: 217,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 4),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 485,
                child: Text(
                  'Programación',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 517,
                child: Text(
                  'Prof. Rodriguez - Lab 101',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 541,
                child: Text(
                  '4:00 PM',
                  style: TextStyle(
                    color: const Color(0xFF8B5CF6),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 551,
                top: 484,
                child: Text(
                  '90%',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF10B981),
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 542,
                top: 521,
                child: Text(
                  'Promedio',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 579,
                child: Text(
                  'Evaluaciones:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 155,
                top: 577,
                child: Text(
                  '4',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 500,
                top: 579,
                child: Text(
                  'Calificadas:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 590,
                top: 577,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 617,
                child: Container(
                  width: 556,
                  height: 37,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFF1F5F9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 634,
                child: Text(
                  'Ver detalles',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 580,
                top: 634,
                child: Container(
                  width: 20,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 648,
                top: 461,
                child: Container(
                  width: 608,
                  height: 217,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 4),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 485,
                child: Text(
                  'Estadística',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 517,
                child: Text(
                  'Prof. Lopez - Aula 108',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 541,
                child: Text(
                  '8:00 AM',
                  style: TextStyle(
                    color: const Color(0xFFEF4444),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1184,
                top: 484,
                child: Text(
                  '83%',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFFFD8305),
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 1174,
                top: 521,
                child: Text(
                  'Promedio',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 579,
                child: Text(
                  'Evaluaciones:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 787,
                top: 577,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 1132,
                top: 579,
                child: Text(
                  'Calificadas:',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1222,
                top: 577,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 617,
                child: Container(
                  width: 556,
                  height: 37,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFF1F5F9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 676,
                top: 634,
                child: Text(
                  'Ver detalles',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 1212,
                top: 634,
                child: Container(
                  width: 20,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1272,
                  height: 80,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      ),BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 4,
                        offset: Offset(0, 2),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 20,
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/40x40"),
                      fit: BoxFit.contain,
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 26,
                child: Text(
                  'ProgreUM',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                  ),
                ),
              ),
              Positioned(
                left: 427,
                top: 28,
                child: Text(
                  'Características',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 581,
                top: 28,
                child: Text(
                  'Beneficios',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 694,
                top: 28,
                child: Text(
                  'Testimonios',
                  style: TextStyle(
                    color: const Color(0xFF64748B),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 1053,
                top: 28,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 1063,
                top: 24,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFD8305),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16777200),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1069,
                top: 25,
                child: Text(
                  '3',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.33,
                  ),
                ),
              ),
              Positioned(
                left: 1093,
                top: 24,
                child: Container(
                  width: 32,
                  height: 32,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/32x32"),
                      fit: BoxFit.contain,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16777200),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1137,
                top: 30,
                child: Text(
                  'Carlos Rodriguez',
                  style: TextStyle(
                    color: const Color(0xFF1E293B),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.43,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}